package com.example.androidsecurityapp.model.availableSettings;

public enum Global {
    ADB_ENABLED, AIRPLANE_MODE_ON, AIRPLANE_MODE_RADIOS, ALWAYS_FINISH_ACTIVITIES, BLUETOOTH_ON,
    BOOT_COUNT, CONTACT_METADATA_SYNC_ENABLED, DATA_ROAMING, DEVELOPMENT_SETTINGS_ENABLED,
    DEVICE_NAME, DEVICE_PROVISIONED, HTTP_PROXY, NETWORK_PREFERENCE, STAY_ON_WHILE_PLUGGED_IN,
    USB_MASS_STORAGE_ENABLED, USE_GOOGLE_MAIL, WIFI_ON, WIFI_WATCHDOG_ON
}
