package com.example.androidsecurityapp.availableSettings;

public enum Secure {
    ACCESSIBILITY_DISPLAY_INVERSION_ENABLED, ACCESSIBILITY_ENABLED, ALLOWED_GEOLOCATION_ORIGINS,
    DEFAULT_INPUT_METHOD, ENABLED_ACCESSIBILITY_SERVICES, ENABLED_INPUT_METHODS, SECURE_FRP_MODE,
    SETTINGS_CLASSNAME, SKIP_FIRST_USE_HINTS, TOUCH_EXPLORATION_ENABLED, TTS_DEFAULT_PITCH
}
