package com.example.androidsecurityapp.availableSettings;

public enum SystemS {
    ACCELEROMETER_ROTATION, ALARM_ALERT, BLUETOOTH_DISCOVERABILITY,
    BLUETOOTH_DISCOVERABILITY_TIMEOUT, END_BUTTON_BEHAVIOR, FONT_SCALE,
    HAPTIC_FEEDBACK_ENABLED, NOTIFICATION_SOUND, MODE_RINGER_STREAMS_AFFECTED,
    RINGTONE, SCREEN_BRIGHTNESS, SCREEN_BRIGHTNESS_MODE, SCREEN_OFF_TIMEOUT,
    SOUND_EFFECTS_ENABLED, TEXT_AUTO_CAPS, TEXT_AUTO_PUNCTUATE, TEXT_AUTO_REPLACE,
    TEXT_SHOW_PASSWORD, TIME_12_24, USER_ROTATION, VIBRATE_ON, VIBRATE_WHEN_RINGING, HIGH_CONTRAST
}
